<a href="https://colab.research.google.com/github/jiwon-min98/LearningPyTorch/blob/main/00_PytorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` : https://pytorch.org/docs/stable/tensors.html

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
 vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

### Random tensors

Why random tensors?
Random tensors are important because the way many neural networks lean is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

https://pytorch.org/docs/stable/generated/torch.rand.html

In [34]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3417, 0.6040, 0.4234, 0.9788],
        [0.7410, 0.1290, 0.5374, 0.8252],
        [0.2465, 0.6227, 0.8495, 0.1732]])

In [39]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [45]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [47]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [48]:
ones.dtype

torch.float32

In [49]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [54]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
# Creating tensors-like
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor dataypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [63]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # default : cpu
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [64]:
float_32_tensor.dtype

torch.float32

In [66]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [67]:
 float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [69]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [70]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [71]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4831, 0.7245, 0.4442, 0.8989],
        [0.5438, 0.7339, 0.1626, 0.0648],
        [0.2125, 0.1943, 0.6274, 0.9373]])

In [75]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4831, 0.7245, 0.4442, 0.8989],
        [0.5438, 0.7339, 0.1626, 0.0648],
        [0.2125, 0.1943, 0.6274, 0.9373]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [84]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [85]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [87]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [88]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [89]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
2. the resulting matrix has the shape of the **outer dimensions.

In [91]:
# Element wise
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [92]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [93]:
%%time
value = 0
for i in range(len(tensor)):
  value+= tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.04 ms, sys: 0 ns, total: 1.04 ms
Wall time: 999 µs


In [94]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 60 µs, sys: 3 µs, total: 63 µs
Wall time: 68.4 µs


tensor(14)

One of the most common errors in deep learning is shape errors

In [97]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7, 10],
                         [8,11],
                         [9,12]])
# torch.mm() = torch.matmul()
torch.matmul(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

To fix out tensor shape issues, we can manipulate the shape of one of our tensors using a **transpost**.


A **transpose** switches the axes or dimensions of a given tensor.

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [99]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [100]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [101]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [102]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatypes to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [103]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [104]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [106]:
# Find the position in tensor that has the minimum value with argmin()
x.argmin()

tensor(0)

In [108]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezzing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or next to eachc other (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view fo the input with dimensions permuted (swapped) ina certain way

In [119]:
# Create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [120]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [121]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [122]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [124]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [129]:
# Squeeze tensor
x_squeezed= x_reshaped.squeeze()
x_reshaped.squeeze().shape

torch.Size([9])

In [132]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed.shape

torch.Size([9, 1])

In [135]:
# torch.permute
x_original = torch.rand(size=(224,224,3))

# permute the original tensor to rearrage the axix (or dim) order
x_permuted = x_original.permute(2, 0, 1 )

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)
Indexing with pytorch is similar to indexing with NumPy

In [137]:
# Create a tensor
import torch
x = torch.arange(1,10). reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [138]:
# Let's index on out new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [139]:
# Let's index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [141]:
# Let's index on the most inner bracket
x[0][0][0]

tensor(1)

In [142]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [143]:
# Get all values of 0ths and 1st dimensions but only index 1 of the 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [144]:
# Get all values of the 0 dimensions but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

 ## PyTorch tensors & NumPy
 NumPy is a popular scientific Python numerical computing library
 And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarry)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [147]:
import torch
import numpy as np

array = np.arange(1.0,9.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch reflects numpy's default datatype of float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [148]:
# Change the value of array
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [149]:
# tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor= tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again...`

In [151]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8915, 0.5760, 0.6652, 0.7161],
        [0.6969, 0.3752, 0.7097, 0.9708],
        [0.4553, 0.8892, 0.1704, 0.0518]])
tensor([[0.0073, 0.8183, 0.4043, 0.4868],
        [0.4359, 0.4593, 0.0684, 0.4912],
        [0.3944, 0.8996, 0.2566, 0.1338]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [153]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (And making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes.

### 1. Getting a GPU
1. Easiest - Use Google Colab for a free GPU
2. Use your own GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computer on the cloud and access them

## 2. Check for GPU access with Pytorch

In [158]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

In [160]:
# Setup device agnostic code
device ="cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [161]:
# Count number of devices
torch.cuda.device_count()

0

## 3. Putting tensor (and models) on the GPU

Using a GPU results in faster computations

## Moving tensors back to the CPU
If tensor is on GPU, can' transform it to Numpy